//Creating a list of 3 orders using the initial data as a base and modifying each slightly
const orders = [
    {
        "supplier": "SUPPLIER SHOP SDN BHD",
        "order_id": "#85258 - 4893",
        "status": "Completed",
        "amount": "MYR 3,920.68",
        "order_created": "08/10/2023",
        "number_of_products": 23,
        "channel": "Platform",
        "promo_code": "None Applied",
        "fulfillment": "Poslaju",
        "delivered_on": "12/10/2023",
        "payment_method": "Platform Credit",
        "payment_status": "Payment Due",
        "payment_due": "11/12/2023",
        "tracking_number": "ABX123145",
    },
    {
        "supplier": "Teguh Maju Mantul SDN BHD",
        "order_id": "#85259 - 4894",
        "status": "Completed",
        "amount": "MYR 1,850.40",
        "order_created": "10/10/2023",
        "number_of_products": 12,
        "channel": "Platform",
        "promo_code": "WELCOME10",
        "fulfillment": "J&T Express",
        "delivered_on": "14/10/2023",
        "payment_method": "Platform Credit",
        "payment_status": "Paid",
        "payment_due": "10/12/2023",
        "tracking_number": "JTX567890",
    },
    {
        "supplier": "Yang Terpaling Supplier Sdn Bhd",
        "order_id": "#85260 - 4895",
        "status": "Pending",
        "amount": "MYR 2,475.90",
        "order_created": "12/10/2023",
        "number_of_products": 17,
        "channel": "Platform",
        "promo_code": "FREESHIP",
        "fulfillment": "DHL",
        "delivered_on": "Pending",
        "payment_method": "Platform Credit",
        "payment_status": "Payment Due",
        "payment_due": "15/12/2023",
        "tracking_number": "DHL987654",
    }
]
